apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: orderservicecontainer
        image: pallavisharma2020/microservices-kubernetes-nagp:order-service
        ports:
        - containerPort: 8081